markdown: rdiscount 
permalink: /:categories/:title 
title: 梦想天空
url: http://dreamsky.github.com/JekyllDemo
subscribe: http://dreamsky.github.com/JekyllDemo/feed.xml
exclude: [ README.md, newpost.rb ]
domain: dreamsky.github.com
author: dreamsky
email: lhb25@163.com
auto: true
twitterID: ycf
duoshuoShortname: sync
navigation:
- text: Home
  url: / 
- text: Archive
  url: /archive/
- text: About
  url: /about/
- text: Links
  url: /links/
