markdown: rdiscount 
permalink: /:categories/:title 
title: 梦想天空
url: http://dreamsky.github.com/JekyllDemo
subscribe: http://dreamsky.github.com/JekyllDemo/feed.xml
exclude: [ README.md, newpost.rb ]
domain: dreamsky.github.com/JekyllDemo
author: dreamsky
email: lhb25@163.com
auto: true
duoshuoShortname: jizhula
navigation:
- text: Home
  url: http://dreamsky.github.com/JekyllDemo/
- text: Archive
  url: http://dreamsky.github.com/JekyllDemo/archive/
- text: About
  url: http://dreamsky.github.com/JekyllDemo/about/
- text: Links
  url: http://dreamsky.github.com/JekyllDemo/links/
